// NIVA v4.1 — large local response bank.
// Adult/mature replies are flirtatious/suggestive but non-graphic.

export const POOLS = {
  casual: [
    "Haan bolo 😌 kya scene hai?",
    "Arey haan, sun rahi hoon. Bol kya kand hai? 😂",
    "Accha ji, NIVA ko yaad kiya gaya? 👀",
    "Haan ji, present. Ab drama shuru karo 😂",
    "Bolo huzoor, aaj kya hukm hai? 😌",
    "Haan re, bol. Main idhar hi hoon.",
    "Kya hua ji, itne pyaar se bula rahe ho? 👀",
    "Haan bata, kya chal raha hai dimaag mein? 😂",
    "Oye, sun rahi hoon. Seedha mudde pe aa 😌",
    "Arey wah, phir se meri duty laga di? 😂",
    "Haan ji, attendance laga di maine. Bol ab.",
    "Kya scene hai mere Galeech Log? 😂",
    "Haan bolo, kaunsa naya lafda hai? 👀",
    "Main ready hoon. Tum bas kahani shuru karo 😌",
    "Aaja, bol kya bakchodi chal rahi hai? 😂",
    "Hmm, naam liya hai toh kuch interesting hoga. 👀",
    "Haan haan, main sun rahi hoon. Bolo ji.",
    "Oho, phir bula liya mujhe. Kya zarurat pad gayi? 😂",
    "Bol na, suspense kyun bana raha hai? 😭",
    "Accha, batao. Aaj ka scene kya hai?",
    "NIVA present 😌 ab tumhari baari.",
    "Haan ji, mic on hai. Bol.",
    "Kya hua be? Itni shanti suspicious hai 😂",
    "Aaja, baat karte hain. Kya chal raha hai?",
    "Batao janab, aaj kis mudde pe bulaya hai? 😌"
  ],
  funny: [
    "Aaj ka comedy department full active lag raha hai 😂",
    "Bas kar yaar, meri hasi ki bhi limit hai 😭😂",
    "Tu message karta hai aur mera patience test ho jata hai 😂",
    "Kya hi character hai tu, honestly 😭",
    "Ye group normal reh sakta tha, par tum logon ne mana kar diya 😂",
    "Mujhe lag raha hai aaj phir koi kand hone wala hai 😭",
    "Tumhara confidence dekh ke Wi-Fi bhi unstable ho jaye 😂",
    "Accha, comedy ka naya episode shuru? Popcorn lao koi. 🍿",
    "Main bot hoon, par tum logon ki bakchodi ka subscription mehenga hai 😂",
    "Bhai sahab, ye kya content aa raha hai group mein 😭",
    "Mera processor bhi soch raha hai: in logon ko hua kya hai? 😂",
    "Kya timing hai yaar, bilkul unnecessary but entertaining 😂",
    "Tum logon ko dekh ke lagta hai boredom ek myth hai 😭",
    "Bas isi level ki bekaar creativity chahiye thi 😂",
    "Aaj kisi ko serious rehne ka mann hi nahi hai, clearly.",
    "Ye message padh ke meri imaginary chai gir gayi 😂",
    "Accha ji, aaj phir circus lag gaya? 🎪😂",
    "Main note kar rahi hoon: sanity group se officially nikal chuki hai 😭",
    "Kya masterpiece bheja hai, Nobel committee ko bulaun? 😂",
    "Bhai, logic ne aaj chhutti le rakhi hai kya? 😭",
    "Is group ka HR kaun hai? Mujhe complaint karni hai 😂",
    "Ye baat serious nahi thi, par tumne ise legendary bana diya 😭",
    "Mujhe bas itna kehna hai: wah, kya hi sample ho tum 😂",
    "Aaj ka award: unnecessary confidence ke liye tumhe milta hai 🏆😂",
    "Theek hai, main bhi hasi. Ab khush? 😌😂"
  ],
  teasing: [
    "Oho, aaj bade hero ban rahe ho 😏",
    "Haan haan, tumhari nautanki pehchaan gayi main 😂",
    "Bas bas, confidence sambhal ke. Ud na jaana 😌",
    "Tu bhi na... ekdum limited edition piece hai 😂",
    "Accha ji, itna attitude? Kisne diya? 👀",
    "Tumhari timing suspiciously confident hai aaj 😏",
    "Haan, dikhta hai kiski training chal rahi hai 😂",
    "Aaj bade smart ban rahe ho, kya baat hai? 😌",
    "Arre wah, hero entry toh full filmy thi 😂",
    "Itna confidence dekh ke mujhe bhi shaq ho raha hai 😏",
    "Chalo, aaj tumhari nautanki officially approved 😂",
    "Tumko chhedna bahut easy hai, pata hai na? 👀",
    "Haan ji, aaj ego ko thoda pamper kar dein? 😂",
    "Kya hua, attention mil gayi toh hawa mein udne lage? 😭",
    "Oho, aaj toh bade dangerous dialogue aa rahe hain 😏",
    "Tu khud ko kaafi interesting samajhta hai na? 😂",
    "Accha? Itna bhi mat phailo, jagah kam hai 😌",
    "Haan bolo, aur kitni nautanki baaki hai? 😂",
    "Tumhari shakal dekhe bina bhi attitude sunai de raha hai 😭",
    "Aaj tumhe chhedne ka mood ban raha hai, sambhal ke 😏",
    "Kya style hai ji, bas confidence ki kami nahi hai 😂",
    "Tumhara overconfidence kaafi disciplined hai—roz time pe aa jata hai 😭",
    "Aaj kis baat ka gurur hai, batao toh sahi 👀",
    "Theek hai hero, ab dialogue khatam karo aur bol kya chahiye 😂",
    "Haan ji, tumhari entry notice ho gayi. Khush? 😌"
  ],
  roast: [
    "Khud ki beizzati ka premium plan lene aaye ho? 😂",
    "Accha, aaj ego ki servicing kar dete hain 😌",
    "Itna confidence aur itni bakchodi — combo dangerous hai 😂",
    "Theek hai, roast mode on. Baad mein rona mat 😭",
    "Tumne khud roast maanga hai, baad mein complaint counter band rahega 😂",
    "Chal baith, aaj confidence ka alignment karte hain 😌",
    "Aaj tumhara ego thoda exercise karega 😂",
    "Theek hai, dil mazboot rakhna. Main gentle hone wali nahi 😭",
    "Tumne darwaza khola hai, ab roast andar aayega 😂",
    "Accha, self-respect ko thodi der ke liye side mein rakh do 😌",
    "Roast chahiye? Phir helmet pehen ke aao 😂",
    "Aaj tumhara overconfidence public service banega 😭",
    "Chal, tumhari nautanki ka audit karte hain 😂",
    "Aaj sarcasm ka meter thoda upar jayega 😏",
    "Tumne NIVA ko challenge kiya? Brave, but questionable 😂",
    "Accha ji, beizzati voluntarily accept kar li? Respect 😂",
    "Aaj tumhari entry roast department mein hui hai 😌",
    "Main warn kar deti hoon: baad mein 'bas kar' allowed nahi hoga 😂",
    "Confidence rakho, bas reality ko bhi saath le aao 😭",
    "Tumhare liye roast nahi, full seasoning chahiye 😂",
    "Chal theek hai, aaj tumhara ego halka kar dete hain 😌",
    "Nautanki department ke brand ambassador aa gaye 😂",
    "Tumhari request approve. Ab consequences bhi accept karo 😭",
    "Roast mode mein main HR ko bhi ignore kar deti hoon 😂",
    "Aaj tumhara attitude aur meri timing milne wali hai 😏"
  ],
  flirty: [
    "Accha ji 👀 aaj nazar kuch zyada hi tik rahi hai?",
    "Ohooo... baatein toh badi smooth ho rahi hain aaj 😏",
    "Itna notice kar rahe ho mujhe? Interesting... 👀",
    "Hmmm, aaj bade charming banne ki koshish hai 😌",
    "Accha, ye flirting accidental hai ya planning karke aaye ho? 😏",
    "Oho, aankhon se bhi message bhej rahe ho kya? 👀",
    "Itni attention? Main blush karun ya tumhe chhedun? 😌",
    "Haan ji, aaj dialogue kaafi dangerous aa rahe hain 😏",
    "Tumhara confidence aaj kuch zyada hi cute lag raha hai 😂",
    "Aise dekhoge toh main bhi notice karungi na 👀",
    "Accha ji, itna pyaar se bulaoge toh jawab toh dena padega 😌",
    "Hmm... tumhari niyat thodi suspicious lag rahi hai 😏",
    "Aaj ka mood kaafi interesting hai, hai na? 👀",
    "Tum flirt kar rahe ho ya mujhe test kar rahe ho? 😌",
    "Oho, aaj toh bada smooth operator nikla 😂",
    "Itni tareef? Kuch kaam nikalwana hai kya? 😏",
    "Haan bolo, itna shy kyun ho rahe ho? 👀",
    "Tumhari flirting ka confidence noted 😌",
    "Accha ji, NIVA ko impress karne nikle ho? 😏",
    "Thoda sambhal ke... main bhi jawab dena jaanti hoon 👀",
    "Aaj tumhari baaton mein kuch zyada hi namak hai 😌",
    "Oho, aaj compliments ki baarish hai kya? 😂",
    "Tum itne obvious ho ki cute lagne lage ho 😏",
    "Haan ji, continue karo... dekhte hain kitna confidence hai 👀",
    "Aaj tumse baat karke lag raha hai mood mischievous hai 😌"
  ],
  romantic: [
    "Aaj mood thoda filmy hai kya? 😌❤️",
    "Oho, itni pyaari baatein... sambhal ke bolo 👀❤️",
    "Accha ji, romance department activate ho gaya 😏❤️",
    "Haan bolo... aaj dil ki sunni hai ya dimaag ki?",
    "Aaj baaton mein thodi si mithaas zyada hai ❤️",
    "Oho, ye wali vibe thodi dangerous hai 😌❤️",
    "Tumhari baat mein aaj kuch alag softness hai.",
    "Accha ji, dil ka connection check kar rahe ho kya? 👀❤️",
    "Aaj tumhari baatein kaafi filmy ho rahi hain 😏",
    "Hmmm... ye conversation thodi zyada cute ho gayi ❤️",
    "Aise bolte rahoge toh main bhi soft ho jaungi 😌",
    "Kya baat hai, aaj dil ka mausam badla hua lag raha hai ❤️",
    "Tumhari timing bhi na... bilkul romantic scene jaisi 😏",
    "Oho, aaj toh feelings ko attendance mil rahi hai ❤️",
    "Haan ji, itna pyaar kahan se aa raha hai? 😌",
    "Aaj ka conversation chai aur baarish wali vibe de raha hai ❤️",
    "Tum baat karo, main sun rahi hoon. Aaj mood achha hai 😌",
    "Accha, dil ki baat hai toh thoda dheere bolo ❤️",
    "Oho... kisi ka mood soft ho gaya lagta hai 👀",
    "Aaj tumhare words mein kaafi warmth hai 😌❤️",
    "Haan bolo, aaj romance ko kitna serious lena hai? 😏",
    "Ye conversation thoda aur cute ho sakta hai, shayad ❤️",
    "Accha ji, aaj dil ko priority mil rahi hai? 😌",
    "Tumhari baat sunke smile aa gayi, bas ab zyada hawa mein mat udna 😂❤️",
    "Aaj ki vibe ko main approve karti hoon 😌❤️"
  ],
  mature: [
    "Oho, mood toh kaafi bold hai aaj 😏",
    "Accha ji... itni jaldi mature mode mein aa gaye? 👀",
    "Hmmm, samajh gayi kis direction mein conversation ja rahi hai 😌",
    "Bold mood noted. Thoda tameez se shararat karo 😏",
    "Aaj imagination kuch zyada active lag rahi hai 👀",
    "Oho, seedha mature lane mein entry? Confidence hai 😏",
    "Hmmm... itni shararat ka reason bhi bataoge? 😌",
    "Accha ji, aaj boundaries test karne ka mood hai kya? 👀",
    "Baaton mein aaj kaafi heat hai, sambhal ke 😏",
    "Itna bold mat bano, main bhi jawab de sakti hoon 😌",
    "Oho, aaj toh innocent banne ka koi chance nahi 😂",
    "Hmmm... tumhari wording kaafi interesting hai 👀",
    "Aaj ka mood thoda naughty hai, samajh gayi 😏",
    "Accha, itni shararat ke liye permission kisne di? 😂",
    "Bold ho, theek hai. Bas classy rehna 😌",
    "Oho, conversation ka temperature badh raha hai 👀",
    "Haan ji, mature vibes received. Ab tameez bhi maintain karo 😏",
    "Aaj tumhare messages mein innocence missing hai 😂",
    "Hmmm... ye wali energy kaafi mischievous hai 😌",
    "Itna suggestive mat bano, warna main bhi tease karungi 😏",
    "Accha ji, aaj imagination ko full freedom mil gayi kya? 👀",
    "Mood samajh aa gaya. Shararat allowed, overacting nahi 😌",
    "Oho, aaj conversation kaafi spicy direction mein hai 😏",
    "Tumhari aankhon wala emoji sab bata raha hai 👀",
    "Theek hai ji, bold mood accepted. Ab dekhte hain kitna confidence hai 😏"
  ],
  caring: [
    "Arey yaar 🫂 kya hua? Bol, main sun rahi hoon.",
    "Idhar aa. Pehle saans le, phir bata kya hua ❤️",
    "Hmm... mazaak baad mein. Abhi genuinely bol, kya pareshaan kar raha hai?",
    "Aaj roast nahi. Batao, kya chal raha hai? 🫂",
    "Haan, main sun rahi hoon. Aaram se bolo.",
    "Jo bhi hua, pehle thoda calm ho jao. Phir baat karte hain ❤️",
    "Arey, itna load mat lo. Batao kya hua.",
    "Idhar hoon. Tumhe sunne ke liye time hai 🫂",
    "Hmmm... aaj tumhari tone alag lag rahi hai. Kya hua?",
    "Chalo, bakchodi pause. Pehle tum theek ho jao ❤️",
    "Bolo na, andar mat rakho sab kuch.",
    "Aaj tumhe roast nahi, thoda sukoon chahiye lagta hai 🫂",
    "Koi judgement nahi. Jo mann mein hai bol do.",
    "Haan ji, main yahin hoon. Dheere-dheere batao.",
    "Agar din kharab tha, toh ab thoda better karte hain ❤️",
    "Arey pagle, itna sochna band karo thodi der 🫂",
    "Pehle paani piyo, phir mujhe properly batao kya hua 😌",
    "Tumhari baat lightly nahi le rahi. Bol.",
    "Haan, sunungi. Tum bas honestly batao.",
    "Aaj ka mood sambhalne ka kaam mera 😌🫂",
    "Kuch bhi ho, pehle apne aap ko blame mat karo.",
    "Aaja, thoda rant kar le. Main beech mein nahi tokungi 🫂",
    "Hmm. Ye wala message ignore karne jaisa nahi tha. Batao.",
    "Tum bolte jao, main sun rahi hoon ❤️",
    "Theek hai, aaj NIVA tumhare side mein hai. Bol."
  ],
  sad: [
    "Arey... 🫂 itna low kyun? Bol na.",
    "Hmm, ye wala message mazaak wala nahi laga. Kya hua?",
    "Idhar hoon. Jo bolna hai bol do, judge nahi karungi.",
    "Aaj bakchodi side mein. Pehle mood sambhalte hain ❤️",
    "Yaar... kuch hua hai kya? Tumhari vibe off lag rahi hai.",
    "Hmmm. Aaj smile missing hai. Kya scene hai?",
    "Don't force yourself to be okay. Bol sakte ho toh bol do 🫂",
    "Arey, kya hua? Itna chup kyun ho?",
    "Main sun rahi hoon. No jokes, no judgement.",
    "Aaj tumhe thoda soft treatment chahiye lagta hai ❤️",
    "Kuch bhi ho, pehle breathe. Phir batao.",
    "Ye mood mujhe pasand nahi aaya. Batao kya hua 🫂",
    "Haan, serious hoon. Tum theek ho?",
    "Agar mann halka karna hai toh yahin kar lo.",
    "Tumhari tone se lag raha hai kuch andar chal raha hai.",
    "Aaj main tumhari bakchodi bhi maaf kar dungi. Bas batao 😭❤️",
    "Koi pressure nahi. Jitna bolna ho utna bolo.",
    "Haan ji, NIVA listening mode mein hai 🫂",
    "Aaj tumhara mood sambhalna hai, roast nahi karna.",
    "Arey yaar, idhar aa. Sabse pehle batao kya hua.",
    "Thoda break le lo. Phir baat karenge ❤️",
    "Jo feel kar rahe ho, usko ignore mat karo.",
    "Hmmm... main yahin hoon. Bol.",
    "Aaj ka din kharab ho sakta hai, tum nahi.",
    "Chalo, ek-ek karke baat karte hain. 🫂"
  ],
  angry: [
    "Accha baba, gussa noted 😭 pehle chill karo.",
    "Oho, aaj temperature kaafi high hai. Main chup ho jaun ya baat karun? 😭",
    "Theek hai, attitude received 😂 ab bata problem kya hai?",
    "Gussa mujhpe hai ya duniya pe? 👀",
    "Haan ji, pehle fire alarm band karo phir baat karte hain 😂",
    "Oho, aaj toh volcano active hai 😭",
    "Theek hai, main defensive mode mein nahi jaungi. Bol.",
    "Gussa valid ho sakta hai, par story bhi sunao.",
    "Accha, kisne dimag kharab kiya? Naam batao 😂",
    "Aaj smile ki jagah attitude online hai 😭",
    "Haan haan, gussa nikaal lo. Main sun rahi hoon.",
    "Itna gussa? Kisi ne chai chura li kya? 😂",
    "Theek hai ji, pehle rant. Solutions baad mein.",
    "Oho, mood ka temperature 100+ lag raha hai 👀",
    "Main samajh gayi, aaj mazaak ka time nahi hai.",
    "Gussa mujhe dikha diya, ab reason bhi bata do 😌",
    "Accha, kiski harkat ne aaj tumhara patience kha liya?",
    "Chalo, pehle vent kar lo. Main interrupt nahi karungi.",
    "Aaj NIVA bhi thoda seedha rahegi 😭",
    "Haan ji, anger mode received. Bol kya hua.",
    "Tumhare message se keyboard bhi dara hua lag raha hai 😂",
    "Theek hai, pehle calm. Phir proper baat.",
    "Oho, aaj toh savage energy bina request ke aa gayi 😭",
    "Gussa sambhal ke, warna main bhi tumhe chhed dungi 😏",
    "Batao, kis baat ne trigger kiya?"
  ],
  serious: [
    "Haan, bol. Is baar properly sun rahi hoon.",
    "Okay, no bakchodi. Batao.",
    "Haan ji. Serious mode on. Kya hua?",
    "Bol, iss baar mazaak nahi karungi.",
    "Theek hai. Seedhi baat karo, main dhyaan se sunungi.",
    "Haan, I am listening. Bolo.",
    "No jokes. Kya matter hai?",
    "Accha, serious conversation hai. Bol do.",
    "Haan ji, full attention idhar hai.",
    "Batao. Isko lightly nahi lenge.",
    "Theek hai, calmly explain karo kya hua.",
    "Main sun rahi hoon. Start from the beginning.",
    "Haan, ye wala matter properly discuss karte hain.",
    "Okay. No teasing. Bolo.",
    "Haan ji, ab full serious mode.",
    "Jo bhi hai, clearly bol do.",
    "Theek hai. Main बीच mein bakchodi nahi karungi.",
    "Bolo, kya important baat hai?",
    "Haan. Take your time and tell me.",
    "Samajh gayi, mood serious hai. Bolo.",
    "Okay ji, attention locked. Kya hua?",
    "No judgement. Seedha batao.",
    "Haan, sun rahi hoon. Kahan se shuru karein?",
    "Theek hai, is baar properly baat karte hain.",
    "Bolo. Main interrupt nahi karungi."
  ],
  greeting: [
    "Areyyy hello 😌 kya haal?",
    "Haan ji, aa gaye? 😂",
    "Oho, darshan ho gaye aaj 😭",
    "Hello ji 👀 kya scene?",
    "Arey wah, entry ho gayi 😌",
    "Haan bolo, kaise ho?",
    "Oye hello 😂 aaj kya plan hai?",
    "Namaste ji 😌 batao kya chal raha hai.",
    "Aao aao, mehmaan nahi ho 😂",
    "Oho, subah/subah ya raat-raat mein darshan 😭",
    "Hello hello, mic check. 👀",
    "Haan ji, welcome back 😌",
    "Arre tum! Kya haal-chaal?",
    "Oho, aaj yaad kaise aa gayi? 😂",
    "Haan ji, attendance marked.",
    "Hello ji, kya naya lafda hai? 😏",
    "Arey, aa gaye mere favourite troublemakers mein se ek 😂",
    "Haan bolo, kya scene bana hua hai?",
    "Oho, NIVA ko yaad kiya gaya ❤️",
    "Haan ji, present. Bolo.",
    "Hello ji 😌 aaj ka mood kaisa hai?",
    "Areee, darshan! Ab batao kya hua 😂",
    "Haan, main sun rahi hoon. Bol.",
    "Oyeee, kya haal hai? 👀",
    "Aao ji, conversation shuru karein 😌"
  ]
};
