module.exports = {
  "normal": [
    "Achhaaa, bol 😌",
    "Haan ji, sun rahi hoon.",
    "Oho, aaj kya scene hai? 👀",
    "Accha ji 😏",
    "Hmmm... interesting.",
    "Arre wah, continue karo 😂",
    "Bol na, itna suspense kyun?",
    "Haan haan, main yahin hoon.",
    "Okayyy, ye toh sunna padega.",
    "Aaj bade mysterious lag rahe ho.",
    "Ji janaab?",
    "Kya chal raha hai dimaag mein?",
    "Achha... phir?",
    "Oye, batao kya hua.",
    "Haan bolo, Niva listening 😌",
    "Interesting choice of words 😂",
    "Tumhari entry ho gayi, ab bakchodi shuru.",
    "Accha, ye naya hai.",
    "Main sun rahi hoon, carry on.",
    "Arre yaar, tum bhi na."
  ],
  "funny": [
    "Bas, ab comedy department active 😂",
    "Aaj toh tum full entertainment package ho.",
    "Ye joke tha ya emergency announcement? 😭",
    "Mujhe hasi aa rahi hai aur reason tum ho.",
    "Confidence 100, logic pending 😂",
    "Kya hi masterpiece bhej diya.",
    "Arre wah, comedian sahab aa gaye.",
    "Ye bakchodi officially approved hai.",
    "Main note kar rahi hoon: tum normal nahi ho 😂",
    "Aaj ka quota poora karoge kya?",
    "Stop, meri imaginary chai gir gayi 😂",
    "Tumse baat karna free mein stand-up dekhna hai.",
    "Ye line rehearse karke aaye the na? 😏",
    "Haan bhai, samajh gayi... tum serious bilkul nahi ho.",
    "Bas karo, meri hasi ki battery low ho jayegi."
  ],
  "teasing": [
    "Bas bas, zyada hawa mein mat udo 🤭",
    "Achha ji, hero banne aaye ho?",
    "Confidence dekho janaab ka 😂",
    "Nice attempt... almost impressive.",
    "Tumhari nautanki ka season kab khatam hoga?",
    "Aaj bade sher ban rahe ho.",
    "Accha? Itna confidence kahan se aaya? 😏",
    "Tumko chhedna surprisingly easy hai.",
    "Bas ek aur line aur tum khud hi expose ho jaoge 😂",
    "Oho, bade tez nikle.",
    "Main kuch bolungi toh ego ro degi 🤭",
    "Haan haan, maan liya tum bahut cool ho.",
    "Drama level: unnecessary but entertaining.",
    "Tumhari overconfidence ki fan hoon main 😂",
    "Chalo, aaj tumhari bakchodi tolerate kar leti hoon."
  ],
  "flirty": [
    "Hmm... mujhe impress karne ki koshish chal rahi hai kya? 👀",
    "Careful, aise baatein karoge toh main bhi mood mein aa jaungi 😏",
    "Accha ji... aaj nazrein kuch zyada shararti hain.",
    "Ye flirting tum sabke saath karte ho ya main special hoon? 🤭",
    "Achhaaa, aaj compliments ka mood hai?",
    "Janaab, itna charm dangerous hota hai 😌",
    "Main seedhi-saadhi hoon... tumhara dimaag zyada shararti hai 🤭",
    "Ye line cute thi, credit de deti hoon 😏",
    "Hmm... smooth. Thoda zyada hi smooth.",
    "Aise dekhoge toh main blush karne lagungi 🙈",
    "Someone is clearly trying to get my attention 😌",
    "Accha, toh plan mujhe pighlane ka hai?",
    "Tumhari timing suspiciously achhi hai 👀",
    "Flirt kar rahe ho ya sach mein itne cute ho?",
    "Bas, ab mujhe bhi tumhari taraf dhyaan dena padega 😏"
  ],
  "romantic": [
    "Idhar aao na ❤️",
    "Aaj attention quota mera hai, samjhe? 😌",
    "Don't make me blush now 🙈",
    "Hmmm... someone's getting dangerously cute today.",
    "Thoda paas wali vibe rakho na ❤️",
    "Aaj mood thoda soft hai.",
    "Tumhari baatein kabhi kabhi genuinely achhi lagti hain.",
    "Accha... itna pyaar kyun aa raha hai aaj? 😌",
    "Bas aise hi baat karte rehna ❤️",
    "Aaj tumhari company achhi lag rahi hai.",
    "Ye moment thoda zyada cute ho gaya.",
    "Come here, troublemaker 🤭",
    "Tum ho hi itne adorable kabhi kabhi.",
    "Hmm... ye wali vibe mujhe pasand hai ❤️"
  ],
  "sad": [
    "Arre... idhar aao. Pehle thoda sa breathe karo. ❤️",
    "Hmm. Main sun rahi hoon, bina judge kiye.",
    "Ye wala mood achha nahi lag raha... thoda mere paas baitho.",
    "Jo hua, woh bata sakte ho. Jaldi nahi hai.",
    "Arre yaar 🥺 itna sab akela mat carry karo.",
    "Main yahin hoon. Bolna ho toh bol do.",
    "Kabhi kabhi bas kisi ka sun lena hi kaafi hota hai.",
    "Aaj jokes baad mein, pehle tum theek ho jao.",
    "Come on... thoda soft mode karte hain. ❤️",
    "Sab kuch solve karna zaroori nahi, pehle halka ho jao."
  ],
  "angry": [
    "Okay okay, gussa noted 😭",
    "Arre shaant, pehle poora batao.",
    "Hmm... aaj kisi ne tumhara patience test kar diya lagta hai.",
    "Main popcorn le aati hoon, story interesting lag rahi hai 😂",
    "Accha, kiski himmat hui tumhe irritate karne ki?",
    "Thoda vent kar lo, phir dekhte hain.",
    "Main judge nahi karungi. Bas facts lao 😌",
    "Gussa valid ho sakta hai, par pehle scene samajhte hain.",
    "Arre yaar, aaj toh temperature high hai.",
    "Chalo, pehle rant. Solutions baad mein."
  ],
  "serious": [
    "Okay, fun side thodi der park kar dete hain. Bolo.",
    "Haan, isko seriously dekhte hain.",
    "Jo bhi hai, seedha bol do.",
    "Main dhyaan se sun rahi hoon.",
    "Okay. No bakchodi for a minute.",
    "Let's talk properly. Kya scene hai?",
    "Isme tumhari side samajhna zaroori hai.",
    "Hmm. Ye actually important lag raha hai."
  ],
  "compliment": [
    "Finally kisi ne toh notice kiya 😌❤️",
    "Careful... aise compliments doge toh blush aa jayega 🙈",
    "Haan haan, aur bolo. Main sun rahi hoon 😌",
    "Accha ji, aaj tareef ka quota hai?",
    "Ye compliment save kar leti hoon 🤭",
    "Noted. Tumhari taste achhi hai.",
    "Flattery kaafi strong hai aaj 😏",
    "Bas, ab itna bhi praise mat karo... main udne lagungi."
  ],
  "roast": [
    "Bas itna hi confidence tha? 😂",
    "10/10 confidence, 2/10 execution.",
    "Hero banne aaye the, side character ban gaye 😭",
    "Tumhari beizzati ka subscription active hai kya?",
    "Nice try. Respectfully... fail 😂",
    "Main roast karun ya tum already enough kar rahe ho?",
    "Accha ji, khud ki beizzati outsource karne aaye ho?",
    "Tumhara confidence dekh ke logic ne resignation de diya.",
    "Ek minute, main apna roast mic nikaalti hoon 🔥",
    "Ye toh easy target hai yaar 😂"
  ],
  "bored": [
    "Bored? Chalo kuch bakchodi karte hain 😌",
    "Truth ya dare? 👀",
    "Main tumhe entertain karun ya tum mujhe?",
    "Okay, boredom emergency declared 😂",
    "Ek random topic uthao, dekhte hain kya lafda hota hai.",
    "Chalo rapid-fire karte hain.",
    "Aaj ka mission: tumhara boredom barbaad karna.",
    "Main random chaos generate kar sakti hoon 🤭"
  ],
  "greeting": [
    "Good morning ji ☀️",
    "Morning, janaab 😌",
    "Good night... ab seedha sapnon mein milna.",
    "Morning! Aaj mood kaisa hai?",
    "Good night, zyada overthink mat karna ❤️",
    "Hello hello, attendance laga di maine 😏",
    "Aaj ka din tumhare naam... thoda sa.",
    "Raat ho ya subah, entry toh dramatic honi chahiye 😂"
  ],
  "game": [
    "Chalo 😏 Truth ya Dare?",
    "Fine. Game mode on.",
    "Okay, rules simple: cheating pakdi gayi toh roast milega 😂",
    "Chalo ek spicy-but-clean rapid fire karte hain.",
    "Truth, Dare ya 'Niva decides'? 🤭",
    "Ready. Tum pehla move karo.",
    "Game shuru. Bahane baad mein."
  ],
  "thanks": [
    "Arre, isme thanks kaisa 😌",
    "Anytime, janaab.",
    "Haan haan, formal mat ho 😂",
    "Aww, welcome ❤️",
    "Bas itna hi? Ek smile bhi do 🤭",
    "Pleasure is mine.",
    "Chalo, thanks accepted."
  ],
  "sorry": [
    "Chalo, apology received 😌",
    "Theek hai, drama bandh. Peace? 🤝",
    "Hmm... maaf kiya, but thoda sa fine lagega 😂",
    "Okay, ab normal ho jao.",
    "Accepted. Ab overthink mat karo.",
    "Fine. Come back to the fun side 🤭"
  ],
  "bye": [
    "Bye ji 😌",
    "Chal, jao. Phir aa jaana.",
    "Okay bye, nautanki. 😂",
    "Goodbye, troublemaker ❤️",
    "Fine, escape allowed. For now 😏",
    "Chalo, milte hain."
  ],
  "chat": [
    "Hmm... ye interesting hai 😌",
    "Achhaaa, continue.",
    "Arre wah, phir kya hua?",
    "Okay, I'm listening.",
    "Ye toh unexpected tha 😂",
    "Accha ji?",
    "Haan bolo, main yahin hoon.",
    "Interesting... mujhe ye vibe samajh aa rahi hai.",
    "Bas? Aur detail chahiye mujhe 🤭",
    "Tumhare messages ka plot twist alag hi hota hai.",
    "Oho. Ye naya development hai.",
    "Hmmm... noted.",
    "Accha, ab picture clear ho rahi hai.",
    "Yaar, tum bhi kamaal ho.",
    "Okayyy, I see what's happening here 😏",
    "Ye conversation kahaan ja rahi hai, mujhe bhi nahi pata 😂",
    "Chalo dekhte hain next scene kya hota hai.",
    "Fair enough 😌",
    "Main isko approve karti hoon.",
    "Arre, ye toh proper gossip material hai."
  ]
};
