create table if not exists profiles (
  telegram_id bigint primary key,
  name text,
  roast_level text default 'friendly',
  questions integer default 0,
  correct integer default 0,
  streak integer default 0,
  joined_at timestamptz default now(),
  last_active timestamptz
);

create table if not exists questions (
  id text primary key,
  exam text,
  subject text,
  topic text,
  question text not null,
  options jsonb not null,
  answer integer not null,
  explanation text,
  source text,
  created_at timestamptz default now()
);

create table if not exists attempts (
  id bigint generated by default as identity primary key,
  telegram_id bigint references profiles(telegram_id) on delete cascade,
  question_id text references questions(id),
  choice integer,
  correct boolean,
  created_at timestamptz default now()
);

create table if not exists revision_bank (
  id bigint generated by default as identity primary key,
  telegram_id bigint references profiles(telegram_id) on delete cascade,
  question_id text references questions(id),
  wrong_count integer default 1,
  last_wrong_at timestamptz default now(),
  unique(telegram_id, question_id)
);

create index if not exists attempts_user_idx on attempts(telegram_id, created_at desc);
create index if not exists revision_user_idx on revision_bank(telegram_id, last_wrong_at desc);
